### ISSUE TITLE
Complete Events Component

### ISSUE THREAD

**Issue by spragginsdesigns** [spragginsdesigns/Gelateria-Del-Centro-WebApp#3]
### Description
The events section of the web app is currently a placeholder and needs to be filled out, completed, and stylized. It also needs to be made responsive for different screen sizes.

### Tasks

- [ ] Fill out the content for the "Overview of Services", "Benefits", and "FAQ" sections in `events.js`.
- [ ] Add images to the "Image Gallery" section in `events.js`.
- [ ] Create and style a form for the "Inquiry Form" section in `events.js`.
- [ ] Style the events section according to the design mockups (add link to mockups here).
- [ ] Make the events section responsive for different screen sizes.

### Additional Information
Please ensure that the events section matches the overall style and theme of the web app. All changes should be made in a new branch and submitted as a pull request for review.

### Resources
[Wireframe](https://www.sketch.com/s/a8a3f3d1-4834-45e5-8c51-5b9a6c1f510c#Comment)
